# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='data_final',
            field=models.DateField(blank=True, verbose_name='Data Final'),
        ),
    ]
