# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='slug',
            field=models.CharField(blank=True, default='#', help_text='A url do evento. Não deve conter nenhum caractere especial.', max_length=140),
        ),
    ]
