# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('events', '0003_auto_20171006_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='categoria',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.Categories'),
        ),
    ]
