# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', wagtail.wagtailcore.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('corpo', wagtail.wagtailcore.fields.StreamField((('Título', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('Subtítulo', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('Parágrafo', wagtail.wagtailcore.blocks.RichTextBlock()), ('Citação', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('Imagem', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Documento', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('Página', wagtail.wagtailcore.blocks.PageChooserBlock()), ('HTML', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('Embed', wagtail.wagtailembeds.blocks.EmbedBlock())))),
                ('subtitulo', models.CharField(blank=True, help_text='O subtítulo da legenda.', max_length=250)),
                ('legenda', models.CharField(blank=True, help_text='A legenda da imagem principal.', max_length=250)),
                ('date', models.DateField(verbose_name='Data')),
                ('categoria', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.Categories')),
                ('imagem_principal', models.ForeignKey(blank=True, help_text='A imagem principal da notícia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
