# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsindexpage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='descricao',
            field=models.CharField(blank=True, help_text='A descrição que vai aparecer na página que lista as notícias.', max_length=500),
        ),
    ]
