# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20170920_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
