# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 18:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newspage_intro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspage',
            old_name='categories',
            new_name='categorias',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='body',
            new_name='corpo',
        ),
        migrations.RenameField(
            model_name='newspage',
            old_name='intro',
            new_name='subtitulo',
        ),
    ]
