# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20170922_1013'),
        ('news', '0009_auto_20170922_1203'),
    ]

    operations = [
    ]
