# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 19:39
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0019_delete_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('cor', colorful.fields.RGBColorField()),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='CategoryIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('resumo', wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=500)),
                ('legenda', models.CharField(blank=True, help_text='A legenda da imagem principal.', max_length=250)),
                ('categoria', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.Categories')),
                ('imagem_principal', models.ForeignKey(blank=True, help_text='A imagem principal da notícia.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CategoryStaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('corpo', wagtail.wagtailcore.fields.StreamField((('Título', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('Subtítulo', wagtail.wagtailcore.blocks.CharBlock(classname='full title')), ('Parágrafo', wagtail.wagtailcore.blocks.RichTextBlock()), ('Citação', wagtail.wagtailcore.blocks.BlockQuoteBlock()), ('Imagem', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Documento', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('Página', wagtail.wagtailcore.blocks.PageChooserBlock()), ('HTML', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('Embed', wagtail.wagtailembeds.blocks.EmbedBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
