# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20171011_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorystaticpage',
            name='descricao',
            field=models.CharField(blank=True, help_text='A descrição que vai aparecer na página index da categoria.', max_length=500),
        ),
    ]
