# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtaildocs.blocks
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('corpo', wagtail.wagtailcore.fields.StreamField((('Parágrafo', wagtail.wagtailcore.blocks.RichTextBlock()), ('Imagem', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Imagem_FULL', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('Documento', wagtail.wagtaildocs.blocks.DocumentChooserBlock()), ('Página', wagtail.wagtailcore.blocks.PageChooserBlock()), ('HTML', wagtail.wagtailcore.blocks.RawHTMLBlock()), ('Embed', wagtail.wagtailembeds.blocks.EmbedBlock())))),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
