# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170922_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='heading',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
