# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0007_auto_20170922_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='imagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='homepage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
