# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20170922_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='imagem',
        ),
    ]
