# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='url',
        ),
    ]
