# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='imagem',
            field=models.ForeignKey(blank=True, help_text='A imagem de fundo da manchete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='link',
            field=models.URLField(blank=True, help_text='O link para onde a manchete irá redirecionar o usuário.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='titulo',
            field=models.CharField(blank=True, help_text='O título da manchete.', max_length=140),
        ),
    ]
