# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0013_auto_20170922_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='link',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='titulo',
        ),
        migrations.AddField(
            model_name='homepage',
            name='imagem_principal',
            field=models.ForeignKey(help_text='A imagem de fundo da manchete.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='link_principal',
            field=models.URLField(default='#', help_text='O link para onde a manchete irá redirecionar o usuário.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='titulo_principal',
            field=models.CharField(default='Título', help_text='O título da manchete.', max_length=140),
        ),
    ]
