# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20170922_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='imagem_principal',
            new_name='imagem',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='link_principal',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='titulo_principal',
            new_name='titulo',
        ),
    ]
